version: '3.8'

x-network: &NETWORK
  networks:
    internal:

networks:
  internal:
    # name: internal
    # external: true

services:
  helloworld:
    build:
      context: ../..
      dockerfile: build/alpine/Dockerfile
    image: helloworld:1
    container_name: helloworld
    hostname: helloworld
    <<: *NETWORK
    # ports:
    #   - 12345:12345
    # volumes:
    #   - .:/src
    # restart: always
    # tty: true
    environment:
      ENVIRONMENT: $ENVIRONMENT
    # entrypoint: tini --
    # command: tail -f /dev/null
